language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd course-03/project
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

  - docker tag udagram-api-feed blacktechie/udagram-api-feed:v6
  - docker tag udagram-api-user blacktechie/udagram-api-user:v6
  - docker tag udagram-frontend blacktechie/udagram-frontend:v6
  - docker tag reverseproxy blacktechie/reverseproxy
  


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push blacktechie/udagram-api-feed
  - docker push blacktechie/udagram-api-user
  - docker push blacktechie/udagram-frontend
  - docker push blacktechie/reverseproxy
