# Use envFrom to load Secrets and ConfigMaps into environment variables
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-microservice-app
  labels:
    app: udagram-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-microservice-app
  template:
    metadata:
      labels:
        app: udagram-microservice-app
    spec:
      containers:
        - name: app
          image: aws.com/udagram-microservice-app/app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secrets